In [2]:
import torch
import torch.nn as nn

a = torch.randn(10)
# a.view(-1)
print(a, a.view(-1))

tensor([ 0.0966, -0.6841,  0.4711,  0.9043, -1.0118,  1.4150, -0.4599,  0.1538,
        -0.9123,  0.9685])

In [3]:
128 * 0.8

76.8

In [3]:
a = {'a':1, 'b':2}
list(a)

['a', 'b']

In [31]:
2400 * 2800

6720000

In [20]:
import torch
import torch.nn as nn
model = nn.Sequential(nn.BatchNorm2d(5))
for m in model.modules():
    if isinstance(m, nn.BatchNorm2d):
        nn.init.constant_(m.weight, 10) 
        nn.init.constant_(m.bias, 3)
model.eval()
i = torch.zeros(1, 5, 1, 1)
c = m(i)
c


tensor([[[[0.]],

         [[0.]],

         [[0.]],

         [[0.]],

         [[0.]]]], grad_fn=<NativeBatchNormBackward>)

In [20]:
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--foo', nargs='*', type=int, default=[0, 0])
parser.add_argument('--bar', nargs='*')
parser.add_argument('baz', nargs='*')
parser.parse_args('1 2 --bar 1 2'.split())

Namespace(bar=['1', '2'], baz=['1', '2'], foo=[0, 0])

In [17]:
import torch
import torch.nn as nn
i = torch.randn(1, 3, 10, 10)
i.requires_grad = True
a = nn.Sequential(nn.Conv2d(3, 5, 1), nn.BatchNorm2d(5), nn.ReLU(inplace=True), \
    nn.Sequential(nn.Conv2d(5, 10, 1), nn.BatchNorm2d(10)))
c = a(i)
(c.mean()).backward()
for m in a.modules():
    if isinstance(m, nn.BatchNorm2d):
        print(m.weight.grad.data)
        m.weight.grad.data.add_(0.01 * torch.sign(m.weight.data))
        print(m.weight.grad.data)

Sequential(
  (0): Conv2d(5, 10, kernel_size=(1, 1), stride=(1, 1))
  (1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)
tensor([ 1.9793e-10,  3.3640e-09,  3.0400e-09, -3.0344e-09,  2.3600e-09])
tensor([0.0100, 0.0100, 0.0100, 0.0100, 0.0100])
tensor([-3.1324e-09, -1.5618e-09, -6.8735e-10,  4.1441e-09,  4.8793e-09,
        -1.6065e-09, -4.3488e-10, -4.8231e-09, -6.0053e-10, -2.1045e-09])
tensor([0.0100, 0.0100, 0.0100, 0.0100, 0.0100, 0.0100, 0.0100, 0.0100, 0.0100,
        0.0100])
